// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user_info/conf"
	"user_info/internal/biz"
	"user_info/internal/server"
	"user_info/internal/service"
)

// Injectors from wire.go:

func WireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userBizHandler := biz.NewUserBizHandler()
	userInfoService := service.NewUserInfoService(userBizHandler)
	grpcServer := server.NewGRPCServer(confServer, userInfoService, logger)
	httpServer := server.NewHTTPServer(confServer, userInfoService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
